<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <table>
        <thead>
            <tr>
                <td>ID</td>
                <td>Name</td>
                <td>Age</td>
                <td>Email</td>
                <td>Phone</td>
                <td>Gender</td>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($data as $item): ?>
            <tr>
                <td><?php echo $item['id'] ?></td>
                <td><?php echo $item['name'] ?></td>
                <td><?php echo $item['age'] ?></td>
                <td><?php echo $item['email'] ?></td>
                <td><?php echo $item['phone'] ?></td>
                <td><?php echo $item['gender'] ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <a href="http://localhost/csvTask/upload/form">Back</a>
    <p><a href="http://localhost/csvTask/truncate/delete">Truncate Table</a></p>
</body>
</html>