<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
      <form action="http://localhost/csvTask/upload/save" method="POST" enctype="multipart/form-data">
         <input type="file" name="csv" />
         <input type="submit"/>
      </form>
      <p><a href="http://localhost/csvTask/main/show">See records</a></p>
</body>
</html>